apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: alertproxy
  name: alertproxy
spec:
  ports:
    - name: http
      port: 9094
      protocol: TCP
      targetPort: 9094
  selector:
    app.kubernetes.io/name: alertproxy
  type: ClusterIP
